
#新增联动配置
p_add = {
    '每天重复_多动作_任一条件':{"effectiveDateStart":1646668800000,"effectiveDateEnd":1648569600000,"repeatTimeStart":"16:38","repeatTimeEnd":"17:38","repeatDate":"","linkageInfoList":[{"facCategoryId":8068,"deviceParamsOptions":[{"label":"开关状态","value":"ZNZMXT_ZMHL_AUTOTEST"}],"linkageFacType":"2","linkageThresholdList":[{"facParam":"ZNZMXT_ZMHL_AUTOTEST","operator":"gt","thresholdStart":"15","triggerType":"1"},{"facParam":"ZNZMXT_ZMHL_AUTOTEST","operator":"lt","thresholdStart":"13","triggerType":"2","triggerTimeInterval":10,"timeUnit":"1"}],"linkageInfoFacList":None}],"linkageActionInfoList":[{"facCategoryId":8068,"deviceParamsOptions":[{"label":"开关状态","value":"ZNZMXT_ZMHL_AUTOTEST"}],"operationFacType":"2","linkageActionList":[{"actionName":"ZNZMXT_ZMHL_AUTOTEST","actionValue":"30"}],"linkageActionInfoFacList":None}],"modeName":"模式名称123","repeatRate":"daily","triggerCondition":"1","remark":"remarkremark"},
    '每天重复_多动作_全部条件':{"effectiveDateStart":1646668800000,"effectiveDateEnd":1648656000000,"repeatTimeStart":"16:41","repeatTimeEnd":"17:41","repeatDate":"","linkageInfoList":[{"facCategoryId":8068,"deviceParamsOptions":[{"label":"开关状态","value":"ZNZMXT_ZMHL_AUTOTEST"}],"linkageFacType":"2","linkageThresholdList":[{"facParam":"ZNZMXT_ZMHL_AUTOTEST","operator":"gt","thresholdStart":"16","triggerType":"2","triggerTimeInterval":10,"timeUnit":"2"},{"facParam":"ZNZMXT_ZMHL_AUTOTEST","operator":"ge","thresholdStart":"15","triggerType":"1"}],"linkageInfoFacList":None}],"linkageActionInfoList":[{"facCategoryId":8068,"deviceParamsOptions":[{"label":"开关状态","value":"ZNZMXT_ZMHL_AUTOTEST"}],"operationFacType":"2","linkageActionList":[{"actionName":"ZNZMXT_ZMHL_AUTOTEST","actionValue":"31"}],"linkageActionInfoFacList":None}],"modeName":"fdsafefdafsd","repeatRate":"daily","triggerCondition":"2","remark":"remarkremark123"},
    '每天重复_单动作_设备类型':{"effectiveDateStart":1646668800000,"effectiveDateEnd":1648656000000,"repeatTimeStart":"16:46","repeatTimeEnd":"17:46","repeatDate":"","linkageInfoList":[{"facCategoryId":8068,"deviceParamsOptions":[{"label":"开关状态","value":"ZNZMXT_ZMHL_AUTOTEST"}],"linkageFacType":"2","linkageThresholdList":[{"facParam":"ZNZMXT_ZMHL_AUTOTEST","operator":"eq","thresholdStart":"15","triggerType":"1"}],"linkageInfoFacList":None}],"linkageActionInfoList":[{"facCategoryId":8068,"deviceParamsOptions":[{"label":"开关状态","value":"ZNZMXT_ZMHL_AUTOTEST"}],"operationFacType":"2","linkageActionList":[{"actionName":"ZNZMXT_ZMHL_AUTOTEST","actionValue":"65"}],"linkageActionInfoFacList":None}],"modeName":"asdfasdfasdf","repeatRate":"daily","triggerCondition":"1","remark":"remarkremark123"},
    '每天重复_单动作_具体设备':{"effectiveDateStart":1646668800000,"effectiveDateEnd":1648656000000,"repeatTimeStart":"16:47","repeatTimeEnd":"17:47","repeatDate":"","linkageInfoList":[{"facCategoryId":8068,"facCateId":8068,"deviceParamsOptions":[{"label":"开关状态","value":"ZNZMXT_ZMHL_AUTOTEST"}],"linkageFacType":"1","linkageThresholdList":[{"facParam":"ZNZMXT_ZMHL_AUTOTEST","operator":"lt","thresholdStart":"13","triggerType":"1"}],"linkageInfoFacList":[{"id":3028}]}],"linkageActionInfoList":[{"facCategoryId":8068,"facCateId":8068,"deviceParamsOptions":[{"label":"开关状态","value":"ZNZMXT_ZMHL_AUTOTEST"}],"operationFacType":"1","linkageActionList":[{"actionName":"ZNZMXT_ZMHL_AUTOTEST","actionValue":"80"}],"linkageActionInfoFacList":[{"id":3028}]}],"modeName":"fdsafdsafdsf","repeatRate":"daily","triggerCondition":"1","remark":"remarkremark123"},
    '每周重复':{"effectiveDateStart":1646668800000,"effectiveDateEnd":1648656000000,"repeatTimeStart":"16:49","repeatTimeEnd":"17:49","repeatDate":"3,5","linkageInfoList":[{"facCategoryId":8068,"deviceParamsOptions":[{"label":"开关状态","value":"ZNZMXT_ZMHL_AUTOTEST"}],"linkageFacType":"2","linkageThresholdList":[{"facParam":"ZNZMXT_ZMHL_AUTOTEST","operator":"ge","thresholdStart":"15","triggerType":"1"}],"linkageInfoFacList":None}],"linkageActionInfoList":[{"facCategoryId":8068,"deviceParamsOptions":[{"label":"开关状态","value":"ZNZMXT_ZMHL_AUTOTEST"}],"operationFacType":"2","linkageActionList":[{"actionName":"ZNZMXT_ZMHL_AUTOTEST","actionValue":"20"}],"linkageActionInfoFacList":None}],"modeName":"fdsafdsafe","repeatRate":"weekly","triggerCondition":"1","remark":"remark123123"},
    '每月重复':{"effectiveDateStart":1646668800000,"effectiveDateEnd":1648656000000,"repeatTimeStart":"16:50","repeatTimeEnd":"17:50","repeatDate":"15","linkageInfoList":[{"facCategoryId":8068,"deviceParamsOptions":[{"label":"开关状态","value":"ZNZMXT_ZMHL_AUTOTEST"}],"linkageFacType":"2","linkageThresholdList":[{"facParam":"ZNZMXT_ZMHL_AUTOTEST","operator":"le","thresholdStart":"15","triggerType":"2","triggerTimeInterval":12,"timeUnit":"1"}],"linkageInfoFacList":None}],"linkageActionInfoList":[{"facCategoryId":8068,"deviceParamsOptions":[{"label":"开关状态","value":"ZNZMXT_ZMHL_AUTOTEST"}],"operationFacType":"2","linkageActionList":[{"actionName":"ZNZMXT_ZMHL_AUTOTEST","actionValue":"30"}],"linkageActionInfoFacList":None}],"modeName":"asdfasdfsaefds","repeatRate":"monthly","triggerCondition":"1","remark":"remark12312"},
}
#新增联动配置
p_page = {
    '名称':{"head":{"current":1,"size":10},"body":{"totalCount":0,"modeName":"模式名称"}},
    '启用':{"head":{"current":1,"size":10},"body":{"totalCount":0,"activeState":1}},
    '禁用':{"head":{"current":1,"size":10},"body":{"totalCount":0,"activeState":0}},
    '重置':{"head":{"current":1,"size":10},"body":{"totalCount":0}},
}
#启动禁用联动配置
p_on_off = {
    '启用':{"id":49,"activeState":1},
    '禁用':{"id":49,"activeState":0},
}
#编辑修改联动配置
p_upd = {
    '01':{"effectiveDateStart":1646668800000,"effectiveDateEnd":1648656000000,"repeatTimeStart":"16:38","repeatTimeEnd":"17:38","repeatDate":"0","linkageInfoList":[{"id":119,"linkageModeId":121,"facCategoryId":8102,"remark":None,"delFlag":0,"createdBy":None,"createdDate":None,"lastUpdatedBy":None,"lastUpdatedDate":None,"propertyId":None,"tenantId":None,"revision":None,"deviceParamsOptions":[{"label":"开关状态","value":"ZNZMXT_ZMHL_AUTOTEST"}],"linkageFacType":"2","linkageThresholdList":[{"id":131,"linkageModeId":121,"linkageInfoId":119,"facParam":"ZNZMXT_ZMHL_AUTOTEST","operator":"ge","thresholdStart":"30","thresholdEnd":None,"triggerType":"1","triggerTimeInterval":None,"timeUnit":None,"remark":None,"delFlag":0,"createdBy":None,"createdDate":None,"lastUpdatedBy":None,"lastUpdatedDate":None,"propertyId":None,"tenantId":None,"revision":None},{"id":132,"linkageModeId":121,"linkageInfoId":119,"facParam":"ZNZMXT_ZMHL_AUTOTEST","operator":"eq","thresholdStart":"61","thresholdEnd":None,"triggerType":"2","triggerTimeInterval":5,"timeUnit":"1","remark":None,"delFlag":0,"createdBy":None,"createdDate":None,"lastUpdatedBy":None,"lastUpdatedDate":None,"propertyId":None,"tenantId":None,"revision":None}],"linkageInfoFacList":None}],"linkageActionInfoList":[{"id":117,"linkageModeId":121,"facCategoryId":8102,"remark":None,"delFlag":0,"createdBy":None,"createdDate":None,"lastUpdatedBy":None,"lastUpdatedDate":None,"propertyId":None,"tenantId":None,"revision":None,"deviceParamsOptions":[{"label":"开关状态","value":"ZNZMXT_ZMHL_AUTOTEST"}],"operationFacType":"2","linkageActionList":[{"id":118,"linkageModeId":121,"linkageActionInfoId":117,"actionName":"ZNZMXT_ZMHL_AUTOTEST","actionValue":"123","remark":None,"delFlag":0,"createdBy":None,"createdDate":None,"lastUpdatedBy":None,"lastUpdatedDate":None,"propertyId":None,"tenantId":None,"revision":None}],"linkageActionInfoFacList":None}],"id":121,"modeName":"模式名称3db5c573","repeatRate":"daily","triggerCondition":"2","activeState":0,"remark":"备注a4c0909b","jobId":None,"delFlag":0,"createdBy":1817,"createdDate":1646733838437,"lastUpdatedBy":1817,"lastUpdatedDate":1646733847857,"propertyId":12769,"tenantId":None,"revision":None,"createdByName":None},
    '02':{"effectiveDateStart":1646668800000,"effectiveDateEnd":1648656000000,"repeatTimeStart":"16:46","repeatTimeEnd":"17:46","repeatDate":"3","linkageInfoList":[{"id":876,"linkageModeId":654,"facCategoryId":23977,"remark":None,"delFlag":0,"createdBy":1817,"createdDate":1650681922040,"lastUpdatedBy":1817,"lastUpdatedDate":1650681922040,"propertyId":28655,"tenantId":None,"revision":None,"deviceParamsOptions":[{"label":"开关状态","value":"ZNZMXT_ZMHL_AUTOTEST"}],"linkageFacType":"2","linkageThresholdList":[{"id":1180,"linkageModeId":654,"linkageInfoId":876,"facParam":"ZNZMXT_ZMHL_AUTOTEST","operator":"eq","thresholdStart":"16","thresholdEnd":None,"triggerType":"1","triggerTimeInterval":None,"timeUnit":None,"remark":None,"delFlag":0,"createdBy":1817,"createdDate":1650681922040,"lastUpdatedBy":1817,"lastUpdatedDate":1650681922040,"propertyId":28655,"tenantId":None,"revision":None}],"linkageInfoFacList":None}],"linkageActionInfoList":[{"id":874,"linkageModeId":654,"facCategoryId":23977,"remark":None,"delFlag":0,"createdBy":1817,"createdDate":1650681922040,"lastUpdatedBy":1817,"lastUpdatedDate":1650681922040,"propertyId":28655,"tenantId":None,"revision":None,"deviceParamsOptions":[{"label":"开关状态","value":"ZNZMXT_ZMHL_AUTOTEST"}],"operationFacType":2,"linkageActionList":[{"id":875,"linkageModeId":654,"linkageActionInfoId":874,"actionName":"ZNZMXT_ZMHL_AUTOTEST","actionValue":"23","remark":None,"delFlag":0,"createdBy":1817,"createdDate":1650681922040,"lastUpdatedBy":1817,"lastUpdatedDate":1650681922040,"propertyId":28655,"tenantId":None,"revision":None}],"linkageActionInfoFacList":None}],"id":654,"modeName":"模式名称643acfd3-05e1-4","repeatRate":"weekly","triggerCondition":"1","activeState":0,"remark":"备注b2a58b59-d13","jobId":None,"delFlag":0,"createdBy":1817,"createdDate":1650681922040,"lastUpdatedBy":1817,"lastUpdatedDate":1650681932969,"propertyId":28655,"tenantId":None,"revision":None,"createdByName":None},
}